apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.nameOverride }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - name: f1u
      port: {{ .Values.service.f1uPort }}
      targetPort: {{ .Values.service.f1uPort }}
      protocol: UDP
