apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.multus.zmqInterface.nadName }}-{{ .Values.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": { "ips": true },
          "master": "enp0s8",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "0.0.0.0/0",
                "gw": "10.100.50.222"
              }
            ]
          }
        }
      ]
    }'
