apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullnameOverride }}-config
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end }}
