apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.nameOverride }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - name: zmq-tx
      port: {{ .Values.service.zmqTxPort }}
      targetPort: {{ .Values.service.zmqTxPort }}
      protocol: TCP
    - name: zmq-rx
      port: {{ .Values.service.zmqRxPort }}
      targetPort: {{ .Values.service.zmqRxPort }}
      protocol: TCP
